# Generated by Django 3.2.21 on 2024-01-29 18:11

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=50, validators=[checkout.models.clean_full_name]),
        ),
    ]
