# Generated by Django 3.2.21 on 2024-01-31 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Please enter a correct phone number. Up to 15 digits without spaces allowed.', regex='^(\\+\\d{1,3})?,?\\s?\\d{7,15}$')]),
        ),
    ]
