# Generated by Django 3.2.21 on 2023-12-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_weight', models.IntegerField(blank=True, null=True)),
                ('postal_rates', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
