# Generated by Django 3.2.21 on 2023-12-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name_plural': 'Shipping'},
        ),
    ]
