# Generated by Django 3.2.21 on 2024-01-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Very Good'), (3, 'Neutral'), (2, 'Bad'), (1, 'Very Bad')], default=None),
        ),
    ]
